title: IT-SEC.fail | IT Security blog and CTF writeups.
email: info@it-sec.fail
description: >-
  An IT security blog by IT security people for everyone who cares. 
  Here IT-Security content is posted as well as a lot of write-ups about CTF participations.
baseurl: "" 
url: ""

kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3

remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-feed