title: IT-SEC.fail | IT Security blog and CTF writeups.
email: info@it-sec.fail
description: >-
  An IT security blog by IT security people for everyone who cares. 
  Here IT-Security content is posted as well as a lot of write-ups about CTF participations.
baseurl: "" 
url: ""

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - readme.md
  - blog.md
  - writeups.md
  - ctfs.md
  - about.md

footer: 'Be safe out there! © by IT-SEC.fail | '

style: hacker # dark (default) or light
listen_for_clients_preferred_style: false # true or false (default)
remote_theme: b2a3e8/jekyll-theme-console

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
